server:
  port: 8080 #服务端口号
  
spring:
  application:
    name: userservice #user服务的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务器地址
      discovery:
        cluster-name: HZ #集群名称
        namespace: e4f0deb5-3997-4130-8163-3e454e9cb23f #环境隔离id
        ephemeral: false #是否是临时实例(采用true服务器压力更小)

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #负载均衡规则(优先访问同一集群下服务)

ribbon:
  eager-load:
    enabled: true #开启饥饿加载(服务器启动时加载)
    clients:
    - userservice #指定饥饿加载的服务名称